name: CI

on:
  pull_request:
    branches: ['**']
  push:
    branches: [main]

jobs:
  test:
    name: 'Test'
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - uses: actions/setup-node@v2
        name: Setup node.js and yarn
        with:
          node-version: '12.14.0'
          cache: 'yarn'

      - uses: actions/cache@v2
        id: loom-cache
        name: Restore loom cache
        with:
          path: |
            .loom
            packages/*/build/ts
            packages/*/build/*.tsbuildinfo
          key: ${{ runner.os }}-loom-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-loom-

      - name: Yarn install
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test

      - name: Lint
        run: yarn lint
