name: CI

on:
  pull_request:
    branches: ['**']
  push:
    branches: [main]

jobs:
  test:
    name: 'Test'
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v1
        name: Checkout

      - uses: actions/setup-node@v1
        name: Setup node.js and yarn
        with:
          node-version: 12.14.0

      - name: Get yarn cache directory
        id: yarn-cache-get-dir
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache
        name: Restore yarn cache
        with:
          path: ${{ steps.yarn-cache-get-dir.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - uses: actions/cache@v2
        id: sewing-kit-cache
        name: Restore sewing-kit cache
        with:
          path: |
            .sewing-kit
            packages/*/build/ts
            packages/*/build/*.tsbuildinfo
          key: ${{ runner.os }}-sewing-kit-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-sewing-kit-

      - name: Yarn install
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test

      - name: Lint
        run: yarn lint
